select * from netflix;


1.Which are the top 5 highest-grossing movies in the dataset?

SELECT "TITLE","REVENUE" 
        FROM "netflix" 
		ORDER BY "REVENUE" DESC 
		LIMIT 5;

2.Which top 3 countries are the largest content producers for this library?

SELECT "COUNTRY", COUNT(*) AS 
        movie_count FROM netflix 
		WHERE "COUNTRY" IS NOT NULL
		GROUP BY "COUNTRY" 
		ORDER BY movie_count DESC
		LIMIT 3;
		
	   
3.What is the average revenue for the "Action" vs "Drama" primary  genres?

SELECT 
    SPLIT_PART("GENRES",',', 1) AS primary_genre, 
    AVG("REVENUE") AS avg_revenue 
    FROM netflix 
    WHERE SPLIT_PART("GENRES",',', 1) IN ('Drama', 'Action')
    GROUP BY primary_genre;

4.Which movies have the highest user engagement(measured by vote count)?

SELECT "TITLE", "VOTE_COUNT" 
      FROM netflix
      ORDER BY "VOTE_COUNT" DESC 
      LIMIT 5;

5.Which language movies have the highest average popularity scores?

SELECT "LANGUAGE", AVG("POPULARITY") as avg_pop 
       FROM netflix 
       GROUP BY "LANGUAGE"
       ORDER BY avg_pop DESC 
       LIMIT 3;

6.Who are the top 5 directors based on their average rating(for directors with at least 5 movies)?

SELECT "DIRECTOR", AVG("VOTE_AVERAGE") AS avg_rating 
       FROM netflix
       GROUP BY "DIRECTOR" 
       HAVING COUNT(*) >= 5 
       ORDER BY avg_rating DESC 
       LIMIT 5;

7.What was the total revenue generated by movies added in 2019 compared to the pandemic year 2020?

SELECT "DATE_ADDED", SUM("REVENUE") AS total_revenue 
       FROM netflix
       WHERE "DATE_ADDED" LIKE '%2019%'
	   OR "DATE_ADDED" LIKE '%2020%'
       GROUP BY "DATE_ADDED";

8.Which countries have the highest average movie ratings(minimum 50 movies)?

SELECT "COUNTRY", AVG("VOTE_AVERAGE") AS avg_rating 
       FROM netflix 
       GROUP BY "COUNTRY" 
       HAVING COUNT(*) >= 50 
       ORDER BY avg_rating DESC 
       LIMIT 8;